#!/usr/bin/python3
import pyautogui as pg
import sys

proxy=r'PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ "'
pg.typewrite(proxy)
pg.press("\n")


proxy=r'clear'
pg.typewrite(proxy)
pg.press("\n")
